services:
  game-service:
    build: ./backend/game_service
    container_name: game-service
    volumes:
      - ./backend/game_service:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    networks:
      - transcendence
    environment:
      - LISTEN_PORT=3000
      - MATCHMAKING_URL=${MATCHMAKING_SERVICE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - NODE_ENV=${NODE_ENV}
    command: npm run dev

  matchmaking-service:
    build: ./backend/matchmaking_service
    container_name: matchmaking-service
    volumes:
      - ./backend/matchmaking_service:/app
      - /app/node_modules
      - ./backend/matchmaking_service/data:/app/data
    ports:
      - "3000:3000"
    networks:
      - transcendence
    environment:
      - PORT=${MATCHMAKING_PORT}
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_VERBOSE=${DB_VERBOSE}
      - DATABASE_PATH=${MATCHMAKING_DATABASE_PATH}
      - GAME_SERVICE_URL=${GAME_SERVICE_URL}
      - SERVICE_URL=${MATCHMAKING_SERVICE_URL}
    command: npm run dev

networks:
  transcendence:
    driver: bridge
