services:
  #game-service:
    #build: ./backend/game_service
    #volumes:
     # - ./backend/game_service:/app
    #  - /app/node_modules
    #ports:
     # - "3001:3000"
    #command: npm run dev
   # networks:
  #    - transcendence
 #   environment:
#      - LISTEN_PORT=3000
  matchmaking-service:
    build: ./backend/matchmaking_service
    volumes:
      - ./backend/matchmaking_service:/app
      - /app/node_modules
      - ./backend/matchmaking_service/data:/app/data
    ports:
      - "3000:3000"
    networks:
      - transcendence
    environment:
      - PORT=${MATCHMAKING_PORT}
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_VERBOSE=${DB_VERBOSE}
      - DATABASE_PATH=${MATCHMAKING_DATABASE_PATH}
      - GAME_SERVICE_URL=${GAME_SERVICE_URL}
      - SERVICE_URL=${MATCHMAKING_SERVICE_URL}
    command: npm run dev
    #depends_on:
     # - game-service

networks:
  transcendence:
    driver: bridge
